package Ventanas;

import DBase.DataBase;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {


    public Login() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        
         DataBase db = new DataBase();
          db.Connection();
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Icon = new javax.swing.JLabel();
        jButton_Salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TB_Usuario = new javax.swing.JTextField();
        TB_Clave = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton_Session = new javax.swing.JButton();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon.png"))); // NOI18N
        getContentPane().add(jLabel_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 260, 280));

        jButton_Salir.setBackground(new java.awt.Color(39, 80, 130));
        jButton_Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salir.setText("Salir");
        jButton_Salir.setOpaque(false);
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(39, 80, 130));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario :");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentY(0.6F);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 35, 90, 20);

        TB_Usuario.setBackground(new java.awt.Color(39, 80, 130));
        TB_Usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TB_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        TB_Usuario.setOpaque(false);
        jPanel1.add(TB_Usuario);
        TB_Usuario.setBounds(140, 30, 220, 30);

        TB_Clave.setBackground(new java.awt.Color(39, 80, 130));
        TB_Clave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TB_Clave.setForeground(new java.awt.Color(255, 255, 255));
        TB_Clave.setOpaque(false);
        jPanel1.add(TB_Clave);
        TB_Clave.setBounds(140, 70, 220, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 75, 120, 20);

        jButton_Session.setBackground(new java.awt.Color(39, 80, 130));
        jButton_Session.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Session.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Session.setText("Iniciar Sesión");
        jButton_Session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SessionActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Session);
        jButton_Session.setBounds(220, 130, 150, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 400, 180));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 611));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jButton_SessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SessionActionPerformed
        DataBase db = new DataBase();

        String usuario = TB_Usuario.getText();
        String clave = String.valueOf(TB_Clave.getPassword());
        
         if(db.validar_ingreso(usuario,clave)==1){
                  
                    this.dispose();//libera memoria, las variables ya usadas.

                    JOptionPane.showMessageDialog(null, "Bienvenido\n Has ingresado "
                    + "satisfactoriamente al sistema", "Mensaje de bienvenida",
                    JOptionPane.INFORMATION_MESSAGE);
                    
                    //ingreso al form
                    VentanaOpciones ventanaopciones = null;          
            try {
                ventanaopciones = new VentanaOpciones();
            } catch (Exception ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
                    ventanaopciones.setVisible(true);

     }else {
                    
                    JOptionPane.showMessageDialog(null, "Acceso denegado:\n"
                    + "Por favor ingrese un usuario y/o contraseña correctos", "Acceso denegado",
                    JOptionPane.ERROR_MESSAGE);
            
     }
    }//GEN-LAST:event_jButton_SessionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPasswordField TB_Clave;
    public static javax.swing.JTextField TB_Usuario;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JButton jButton_Session;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JLabel jLabel_Icon;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
