/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import DBase.DataBase;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Francisco
 */
public class VentanaAñadir extends javax.swing.JFrame {

    DataBase db = new DataBase();

    /**
     * Creates new form Ventana1
     */
    public VentanaAñadir() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);

        db.Connection();

        jComboBox_ArtistaDisco.removeAllItems();
        ArrayList<String> listaDisco = new ArrayList<>();
        listaDisco = DataBase.LlenarCombo("artista", "Nombre");
        for (int i = 0; i < listaDisco.size(); i++) {
            jComboBox_ArtistaDisco.addItem(listaDisco.get(i));
        }

        jComboBox_ArtistaCanciones.removeAllItems();
        ArrayList<String> listaCanciones = new ArrayList<>();
        listaCanciones = DataBase.LlenarCombo("artista", "Nombre");
        for (int i = 0; i < listaCanciones.size(); i++) {
            jComboBox_ArtistaCanciones.addItem(listaCanciones.get(i));
        }
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Artista = new javax.swing.JPanel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Origen = new javax.swing.JLabel();
        jLabel_Formacion = new javax.swing.JLabel();
        jLabel_Discos = new javax.swing.JLabel();
        jLabel_Sencillos = new javax.swing.JLabel();
        TB_Nombre = new javax.swing.JTextField();
        TB_Origen = new javax.swing.JTextField();
        TB_Discos = new javax.swing.JTextField();
        TB_Sencillos = new javax.swing.JTextField();
        TB_Formacion = new javax.swing.JTextField();
        jButton_AñadirArtista = new javax.swing.JButton();
        jPanel_Disco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_ArtistaDisco = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TB_NombreDisco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TB_Lanzamiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TB_Duracion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TB_NumCanciones = new javax.swing.JTextField();
        jButton_AñadirDisco = new javax.swing.JButton();
        jPanel_Canciones = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_ArtistaCanciones = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TB_NombreCancion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TB_DuracionCancion = new javax.swing.JTextField();
        jButton_AñadirCancion = new javax.swing.JButton();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Artista.setBackground(new java.awt.Color(49, 93, 146));
        jPanel_Artista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir Artista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_Artista.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_Artista.setPreferredSize(new java.awt.Dimension(300, 436));

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre.setText("Nombre :");

        jLabel_Origen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Origen.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Origen.setText("Origen :");

        jLabel_Formacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Formacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Formacion.setText("Año de Formacion :");

        jLabel_Discos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Discos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Discos.setText("Discos :");

        jLabel_Sencillos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Sencillos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Sencillos.setText("Sencillos :");

        jButton_AñadirArtista.setText("Añadir Artista");
        jButton_AñadirArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AñadirArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ArtistaLayout = new javax.swing.GroupLayout(jPanel_Artista);
        jPanel_Artista.setLayout(jPanel_ArtistaLayout);
        jPanel_ArtistaLayout.setHorizontalGroup(
            jPanel_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ArtistaLayout.createSequentialGroup()
                        .addGroup(jPanel_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Sencillos)
                            .addComponent(jLabel_Discos)
                            .addComponent(jLabel_Origen)
                            .addComponent(jLabel_Nombre)
                            .addComponent(jLabel_Formacion))
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(jPanel_ArtistaLayout.createSequentialGroup()
                        .addGroup(jPanel_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_AñadirArtista)
                            .addGroup(jPanel_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TB_Sencillos, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TB_Discos, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TB_Origen, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TB_Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TB_Formacion, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_ArtistaLayout.setVerticalGroup(
            jPanel_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Nombre)
                .addGap(4, 4, 4)
                .addComponent(TB_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Origen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_Origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Discos)
                .addGap(4, 4, 4)
                .addComponent(TB_Discos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Sencillos)
                .addGap(4, 4, 4)
                .addComponent(TB_Sencillos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Formacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_Formacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_AñadirArtista)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Artista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 360));

        jPanel_Disco.setBackground(new java.awt.Color(49, 93, 146));
        jPanel_Disco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir Disco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_Disco.setPreferredSize(new java.awt.Dimension(300, 436));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Artista :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Disco :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Año Lanzamiento :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Duracion :");

        TB_Duracion.setText("00:00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero de Canciones :");

        jButton_AñadirDisco.setText("Añardir Disco");
        jButton_AñadirDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AñadirDiscoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_DiscoLayout = new javax.swing.GroupLayout(jPanel_Disco);
        jPanel_Disco.setLayout(jPanel_DiscoLayout);
        jPanel_DiscoLayout.setHorizontalGroup(
            jPanel_DiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_AñadirDisco)
                    .addGroup(jPanel_DiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox_ArtistaDisco, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(TB_NombreDisco, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(TB_Lanzamiento)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(TB_Duracion, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(TB_NumCanciones)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel_DiscoLayout.setVerticalGroup(
            jPanel_DiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_ArtistaDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(TB_NombreDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_Lanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_NumCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_AñadirDisco)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Disco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 360));

        jPanel_Canciones.setBackground(new java.awt.Color(49, 93, 146));
        jPanel_Canciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir Cancion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_Canciones.setPreferredSize(new java.awt.Dimension(300, 436));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre Artista :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre Cancion :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Duracion Cancion :");

        TB_DuracionCancion.setText("00:00");

        jButton_AñadirCancion.setText("Añadir Cancion");
        jButton_AñadirCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AñadirCancionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_CancionesLayout = new javax.swing.GroupLayout(jPanel_Canciones);
        jPanel_Canciones.setLayout(jPanel_CancionesLayout);
        jPanel_CancionesLayout.setHorizontalGroup(
            jPanel_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_AñadirCancion)
                    .addGroup(jPanel_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jComboBox_ArtistaCanciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TB_NombreCancion)
                        .addComponent(TB_DuracionCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel_CancionesLayout.setVerticalGroup(
            jPanel_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_ArtistaCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_NombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_DuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_AñadirCancion)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Canciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 200, 360));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        jLabel_Fondo.setMaximumSize(new java.awt.Dimension(700, 600));
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AñadirArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AñadirArtistaActionPerformed
        String Nombre = TB_Nombre.getText();
        String Origen = TB_Origen.getText();
        int Formacion = Integer.parseInt(TB_Formacion.getText());
        int Sencillos = Integer.parseInt(TB_Sencillos.getText());
        int Discos = Integer.parseInt(TB_Discos.getText());

        db.insertArtista(0, Nombre, Origen, Formacion, Sencillos, Discos);
    }//GEN-LAST:event_jButton_AñadirArtistaActionPerformed

    private void jButton_AñadirDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AñadirDiscoActionPerformed
        String id = (String) jComboBox_ArtistaDisco.getSelectedItem();
        int obtenerID = db.obtenerID(id);
        String nombreDisco = TB_NombreDisco.getText();
        int fechaLanzamiento = Integer.parseInt(TB_Lanzamiento.getText());
        String duracion = TB_Duracion.getText();
        int cancionesDisco = Integer.parseInt(TB_NumCanciones.getText());
        db.insertDiscografia(0, obtenerID, nombreDisco, fechaLanzamiento, duracion, cancionesDisco);
    }//GEN-LAST:event_jButton_AñadirDiscoActionPerformed

    private void jButton_AñadirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AñadirCancionActionPerformed
        String id = (String) jComboBox_ArtistaCanciones.getSelectedItem();
        int obtenerID = db.obtenerID(id);
        
        String nombreCancion = TB_NombreCancion.getText();
        String Duracion = TB_DuracionCancion.getText();
        
        db.insertCancion(0, 0, obtenerID, nombreCancion, Duracion);
    }//GEN-LAST:event_jButton_AñadirCancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaAñadir().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaAñadir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TB_Discos;
    private javax.swing.JTextField TB_Duracion;
    private javax.swing.JTextField TB_DuracionCancion;
    private javax.swing.JTextField TB_Formacion;
    private javax.swing.JTextField TB_Lanzamiento;
    private javax.swing.JTextField TB_Nombre;
    private javax.swing.JTextField TB_NombreCancion;
    private javax.swing.JTextField TB_NombreDisco;
    private javax.swing.JTextField TB_NumCanciones;
    private javax.swing.JTextField TB_Origen;
    private javax.swing.JTextField TB_Sencillos;
    private javax.swing.JButton jButton_AñadirArtista;
    private javax.swing.JButton jButton_AñadirCancion;
    private javax.swing.JButton jButton_AñadirDisco;
    private javax.swing.JComboBox<String> jComboBox_ArtistaCanciones;
    private javax.swing.JComboBox<String> jComboBox_ArtistaDisco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Discos;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JLabel jLabel_Formacion;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Origen;
    private javax.swing.JLabel jLabel_Sencillos;
    private javax.swing.JPanel jPanel_Artista;
    private javax.swing.JPanel jPanel_Canciones;
    private javax.swing.JPanel jPanel_Disco;
    // End of variables declaration//GEN-END:variables
}
