package Ventanas;

import DBase.DataBase;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco
 */
public class VentanaBuscar extends javax.swing.JFrame {

    JTable tabla;
    ResultSet rs;
    DataBase db = new DataBase();

    public VentanaBuscar() throws Exception {
        initComponents();

        this.setLocationRelativeTo(null);

        db.Connection();

        RB_ArtistaNombre.setSelected(true);
        RB_NombreDisco.setSelected(true);
        RB_NombreCancion.setSelected(true);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoArtista = new javax.swing.ButtonGroup();
        grupoDisco = new javax.swing.ButtonGroup();
        grupoCancion = new javax.swing.ButtonGroup();
        jPanel_Artista = new javax.swing.JPanel();
        TB_BuscarArtista = new javax.swing.JTextField();
        RB_ArtistaNombre = new javax.swing.JRadioButton();
        RB_ArtistaOrigen = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_BuscarArtista = new javax.swing.JButton();
        jPanel_Disco = new javax.swing.JPanel();
        TB_BuscarDisco = new javax.swing.JTextField();
        RB_NombreDisco = new javax.swing.JRadioButton();
        RB_AñoDisco = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton_BuscarDisco = new javax.swing.JButton();
        jPanel_Cancion = new javax.swing.JPanel();
        TB_BuscarCancion = new javax.swing.JTextField();
        RB_NombreCancion = new javax.swing.JRadioButton();
        RB_NombreArtista = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton_BuscarCancion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Result = new javax.swing.JTable();
        jLabel_Fondo = new javax.swing.JLabel();

        grupoArtista.add(RB_ArtistaNombre);
        grupoArtista.add(RB_ArtistaOrigen);

        grupoDisco.add(RB_NombreDisco);
        grupoDisco.add(RB_AñoDisco);

        grupoCancion.add(RB_NombreCancion);
        grupoCancion.add(RB_NombreArtista);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Artista.setBackground(new java.awt.Color(49, 93, 146));
        jPanel_Artista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Artista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        RB_ArtistaNombre.setBackground(new java.awt.Color(49, 93, 146));
        grupoArtista.add(RB_ArtistaNombre);
        RB_ArtistaNombre.setForeground(new java.awt.Color(255, 255, 255));
        RB_ArtistaNombre.setText("por Nombre");

        RB_ArtistaOrigen.setBackground(new java.awt.Color(49, 93, 146));
        grupoArtista.add(RB_ArtistaOrigen);
        RB_ArtistaOrigen.setForeground(new java.awt.Color(255, 255, 255));
        RB_ArtistaOrigen.setText("por Origen");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresar Busqueda");

        jButton_BuscarArtista.setText("Buscar Artista");
        jButton_BuscarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ArtistaLayout = new javax.swing.GroupLayout(jPanel_Artista);
        jPanel_Artista.setLayout(jPanel_ArtistaLayout);
        jPanel_ArtistaLayout.setHorizontalGroup(
            jPanel_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ArtistaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addComponent(TB_BuscarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RB_ArtistaNombre)
                    .addComponent(RB_ArtistaOrigen))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ArtistaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_BuscarArtista)
                .addContainerGap())
        );
        jPanel_ArtistaLayout.setVerticalGroup(
            jPanel_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RB_ArtistaNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB_ArtistaOrigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_BuscarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_BuscarArtista)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Artista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 180));

        jPanel_Disco.setBackground(new java.awt.Color(49, 93, 146));
        jPanel_Disco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Disco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        RB_NombreDisco.setBackground(new java.awt.Color(49, 93, 146));
        grupoDisco.add(RB_NombreDisco);
        RB_NombreDisco.setForeground(new java.awt.Color(255, 255, 255));
        RB_NombreDisco.setText("por Nombre del Disco");

        RB_AñoDisco.setBackground(new java.awt.Color(49, 93, 146));
        grupoDisco.add(RB_AñoDisco);
        RB_AñoDisco.setForeground(new java.awt.Color(255, 255, 255));
        RB_AñoDisco.setText("por Año de Lanzamiento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresar Busqueda");

        jButton_BuscarDisco.setText("Buscar Disco");
        jButton_BuscarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarDiscoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_DiscoLayout = new javax.swing.GroupLayout(jPanel_Disco);
        jPanel_Disco.setLayout(jPanel_DiscoLayout);
        jPanel_DiscoLayout.setHorizontalGroup(
            jPanel_DiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_BuscarDisco)
                    .addGroup(jPanel_DiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_DiscoLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel2))
                        .addComponent(TB_BuscarDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RB_NombreDisco)
                        .addComponent(RB_AñoDisco)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel_DiscoLayout.setVerticalGroup(
            jPanel_DiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RB_NombreDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB_AñoDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_BuscarDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_BuscarDisco)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Disco, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 200, 180));

        jPanel_Cancion.setBackground(new java.awt.Color(49, 93, 146));
        jPanel_Cancion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Canción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        RB_NombreCancion.setBackground(new java.awt.Color(49, 93, 146));
        grupoCancion.add(RB_NombreCancion);
        RB_NombreCancion.setForeground(new java.awt.Color(255, 255, 255));
        RB_NombreCancion.setText("por Nombre de la Cancion");

        RB_NombreArtista.setBackground(new java.awt.Color(49, 93, 146));
        grupoCancion.add(RB_NombreArtista);
        RB_NombreArtista.setForeground(new java.awt.Color(255, 255, 255));
        RB_NombreArtista.setText("por Nombre del Artista");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresar Busqueda");

        jButton_BuscarCancion.setText("Buscar Cancion");
        jButton_BuscarCancion.setMaximumSize(null);
        jButton_BuscarCancion.setMinimumSize(null);
        jButton_BuscarCancion.setOpaque(false);
        jButton_BuscarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarCancionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_CancionLayout = new javax.swing.GroupLayout(jPanel_Cancion);
        jPanel_Cancion.setLayout(jPanel_CancionLayout);
        jPanel_CancionLayout.setHorizontalGroup(
            jPanel_CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_BuscarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_CancionLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel3))
                        .addComponent(TB_BuscarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RB_NombreCancion)
                        .addComponent(RB_NombreArtista)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel_CancionLayout.setVerticalGroup(
            jPanel_CancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CancionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RB_NombreCancion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB_NombreArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_BuscarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_BuscarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Cancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 200, 180));

        jTable_Result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Result);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 620, 270));

        jLabel_Fondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        jLabel_Fondo.setMaximumSize(new java.awt.Dimension(700, 600));
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BuscarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarDiscoActionPerformed
        DefaultTableModel dfm = new DefaultTableModel();
        tabla = this.jTable_Result;
        tabla.setModel(dfm);
        String valor = TB_BuscarDisco.getText();
        dfm.setColumnIdentifiers(new Object[]{"Nombre Disco", "Año Lanzamiento", "Duracion"});

        // rs = db.busquedaDatos(tabla, columna, valor);
        if (RB_NombreDisco.isSelected() == true) {

            rs = db.busquedaDatos("nombreDisco,fechaLanzamiento,Duracion", "discografia", "nombreDisco", valor);
            try {
                while (rs.next()) {
                    dfm.addRow(new Object[]{rs.getString("nombreDisco"), rs.getInt("fechaLanzamiento"), rs.getString("Duracion")});
                }
            } catch (SQLException ex) {
                //Logger.getLogger(VentanaBuscar.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (RB_AñoDisco.isSelected() == true) {

            rs = db.busquedaDatos("nombreDisco,fechaLanzamiento,Duracion", "discografia", "fechaLanzamiento", valor);
            try {
                while (rs.next()) {
                    dfm.addRow(new Object[]{rs.getString("nombreDisco"), rs.getInt("fechaLanzamiento"), rs.getString("Duracion")});
                }
            } catch (SQLException ex) {
                //Logger.getLogger(VentanaBuscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_BuscarDiscoActionPerformed

    private void jButton_BuscarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarArtistaActionPerformed
        DefaultTableModel dfm = new DefaultTableModel();
        tabla = this.jTable_Result;
        tabla.setModel(dfm);
        String valor = TB_BuscarArtista.getText();
        dfm.setColumnIdentifiers(new Object[]{"Nombre", "Origen", "Formacion"});

        // rs = db.busquedaDatos(tabla, columna, valor);
        if (RB_ArtistaNombre.isSelected() == true) {

            rs = db.busquedaDatos("Nombre,Origen,Formacion", "artista", "Nombre", valor);
            try {
                while (rs.next()) {
                    dfm.addRow(new Object[]{rs.getString("Nombre"), rs.getString("Origen"), rs.getInt("Formacion")});
                }
            } catch (SQLException ex) {
                //Logger.getLogger(VentanaBuscar.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (RB_ArtistaOrigen.isSelected() == true) {

            rs = db.busquedaDatos("Nombre,Origen,Formacion", "artista", "Origen", valor);
            try {
                while (rs.next()) {
                    dfm.addRow(new Object[]{rs.getString("Nombre"), rs.getString("Origen"), rs.getInt("Formacion")});
                }
            } catch (SQLException ex) {
                //Logger.getLogger(VentanaBuscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_BuscarArtistaActionPerformed

    private void jButton_BuscarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarCancionActionPerformed
        DefaultTableModel dfm = new DefaultTableModel();
        tabla = this.jTable_Result;
        tabla.setModel(dfm);
        String valor = TB_BuscarCancion.getText();
        dfm.setColumnIdentifiers(new Object[]{"Nombre Cancion", "Duracion"});

        // rs = db.busquedaDatos(tabla, columna, valor);
        if (RB_NombreCancion.isSelected() == true) {

            rs = db.busquedaDatos("nombreCancion,Duracion", "cancion", "nombreCancion", valor);
            try {
                while (rs.next()) {
                    dfm.addRow(new Object[]{rs.getString("nombreCancion"), rs.getString("Duracion")});
                }
            } catch (SQLException ex) {
                //Logger.getLogger(VentanaBuscar.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (RB_NombreArtista.isSelected() == true) {
            int obtenerID = db.obtenerID(valor);

            rs = db.busquedaDatos("nombreCancion,Duracion", "cancion", "idArtista", String.valueOf(obtenerID));
            try {
                while (rs.next()) {
                    dfm.addRow(new Object[]{rs.getString("nombreCancion"), rs.getString("Duracion")});
                }
            } catch (SQLException ex) {
                //Logger.getLogger(VentanaBuscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_BuscarCancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaBuscar().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaBuscar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RB_ArtistaNombre;
    private javax.swing.JRadioButton RB_ArtistaOrigen;
    private javax.swing.JRadioButton RB_AñoDisco;
    private javax.swing.JRadioButton RB_NombreArtista;
    private javax.swing.JRadioButton RB_NombreCancion;
    private javax.swing.JRadioButton RB_NombreDisco;
    private javax.swing.JTextField TB_BuscarArtista;
    private javax.swing.JTextField TB_BuscarCancion;
    private javax.swing.JTextField TB_BuscarDisco;
    private javax.swing.ButtonGroup grupoArtista;
    private javax.swing.ButtonGroup grupoCancion;
    private javax.swing.ButtonGroup grupoDisco;
    private javax.swing.JButton jButton_BuscarArtista;
    private javax.swing.JButton jButton_BuscarCancion;
    private javax.swing.JButton jButton_BuscarDisco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JPanel jPanel_Artista;
    private javax.swing.JPanel jPanel_Cancion;
    private javax.swing.JPanel jPanel_Disco;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Result;
    // End of variables declaration//GEN-END:variables
}
